language: minimal
dist: xenial

addons:
  apt:
    packages:
      # Travis uses --no-install-suggests and --no-install-recommends so all necessary packages must be explicitly defined
      - lazarus
      - lcl

script:
  - lazbuild -q -q Source/LdapAdmin.lpi
  - tar -cvzf LdapAdmin-linux-64bit.tgz -C Source LdapAdmin

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: LdapAdmin-linux-64bit.tgz
  skip_cleanup: true
  on:
    tags: true
