language: minimal
dist: xenial

addons:
  apt:
    packages:
      - lazarus

before_script:
  - ls LDAP-Admin/Source/LdapAdmin; true

script:
  - lazbuild LDAP-Admin/Source/LdapAdmin.lpi

after_script:
  - ls LDAP-Admin/Source/LdapAdmin
