language: minimal
dist: xenial

addons:
  apt:
    packages:
      - fpc
      - fpc-source
      - lazarus
      - lcl
      - lcl-utils-1.6

before_script:
  - ls -l Source/LdapAdmin; true

script:
  - lazbuild -q -q Source/LdapAdmin.lpi

after_script:
  - ls -l Source/LdapAdmin
  - file Source/LdapAdmin
