language: minimal
dist: xenial

addons:
  apt:
    packages:
      - lcl-utils-1.6

before_script:
  - ls LDAP-Admin/Source/LdapAdmin; true

script:
  - lazbuild Source/LdapAdmin.lpi

after_script:
  - ls LDAP-Admin/Source/LdapAdmin
