language: minimal
dist: xenial

addons:
  apt:
    packages:
      # Travis uses --no-install-suggests and --no-install-recommends so all necessary packages must be explicitly installed
      - lazarus
      - lcl

script:
  # Work around https://github.com/ibv/LDAP-Admin/issues/3
  - sed -i 's/libssl.so/libssl.so.1.0.0/'  Source/synapse/ssl_openssl_lib.pas
  - sed -i 's/libcrypto.so/libcrypto.so.1.0.0/'  Source/synapse/ssl_openssl_lib.pas
  # Without -q -q the build logs exceed the amount Travis will show in the web interface (10k lines)
  - lazbuild -q -q Source/LdapAdmin.lpi
  - tar -cvzf LdapAdmin-linux-64bit.tar.gz -C Source LdapAdmin

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: LdapAdmin-linux-64bit.tar.gz
  skip_cleanup: true
  on:
    tags: true
