language: minimal
dist: xenial

addons:
  apt:
    packages:
      - fpc
      - fpc-source
      - lazarus
      - lcl
      - lcl-utils-1.6

before_script:
  - ls Source/LdapAdmin; true

script:
  - lazbuild -q Source/LdapAdmin.lpi

after_script:
  - ls Source/LdapAdmin
