language: minimal
dist: xenial

addons:
  apt:
    packages:
      # Travis uses --no-install-suggests and --no-install-recommends so all necessary packages must be explicitly defined
      - lazarus
      - lcl

script:
  - lazbuild -q -q Source/LdapAdmin.lpi

deploy:
  provider: releases
  api_key: $GITHUB_OATH_TOKEN
  file: Source/LdapAdmin
  skip_cleanup: true
  on:
    tags: true
