language: minimal
dist: xenial

addons:
  apt:
    packages:
      # Travis uses --no-install-suggests and --no-install-recommends so all necessary packages must be explicitly defined
      - lazarus
      - lcl

script:
  - lazbuild -q -q Source/LdapAdmin.lpi

after_script:
  - ls -l Source/LdapAdmin
  - file Source/LdapAdmin
